// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on InternalContact with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *InternalContact) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	return nil
}

// InternalContactValidationError is the validation error returned by
// InternalContact.Validate if the designated constraints aren't met.
type InternalContactValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InternalContactValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InternalContactValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InternalContactValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InternalContactValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InternalContactValidationError) ErrorName() string { return "InternalContactValidationError" }

// Error satisfies the builtin error interface
func (e InternalContactValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInternalContact.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InternalContactValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InternalContactValidationError{}

// Validate checks the field values on InternalConfig with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *InternalConfig) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Version

	// no validation rules for Status

	for idx, item := range m.GetContacts() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InternalConfigValidationError{
					field:  fmt.Sprintf("Contacts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for UploadDir

	// no validation rules for Users

	// no validation rules for InboundMedia

	if v, ok := interface{}(m.GetApplicationSettings()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InternalConfigValidationError{
				field:  "ApplicationSettings",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetProfileAbout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InternalConfigValidationError{
				field:  "ProfileAbout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetBusinessProfile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InternalConfigValidationError{
				field:  "BusinessProfile",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ProfilePhotoFilename

	// no validation rules for Verified

	// no validation rules for WebhookCA

	return nil
}

// InternalConfigValidationError is the validation error returned by
// InternalConfig.Validate if the designated constraints aren't met.
type InternalConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InternalConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InternalConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InternalConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InternalConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InternalConfigValidationError) ErrorName() string { return "InternalConfigValidationError" }

// Error satisfies the builtin error interface
func (e InternalConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInternalConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InternalConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InternalConfigValidationError{}

// Validate checks the field values on WebhookRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *WebhookRequest) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetContacts() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebhookRequestValidationError{
					field:  fmt.Sprintf("Contacts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebhookRequestValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetStatuses() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebhookRequestValidationError{
					field:  fmt.Sprintf("Statuses[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetErrors() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WebhookRequestValidationError{
					field:  fmt.Sprintf("Errors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for ErrorCounter

	return nil
}

// WebhookRequestValidationError is the validation error returned by
// WebhookRequest.Validate if the designated constraints aren't met.
type WebhookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WebhookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WebhookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WebhookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WebhookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WebhookRequestValidationError) ErrorName() string { return "WebhookRequestValidationError" }

// Error satisfies the builtin error interface
func (e WebhookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWebhookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WebhookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WebhookRequestValidationError{}
