// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_unknown     MessageType = 0
	MessageType_document    MessageType = 1
	MessageType_image       MessageType = 2
	MessageType_location    MessageType = 3
	MessageType_system      MessageType = 4
	MessageType_text        MessageType = 5
	MessageType_video       MessageType = 6
	MessageType_voice       MessageType = 7
	MessageType_audio       MessageType = 8
	MessageType_template    MessageType = 9
	MessageType_interactive MessageType = 10
)

var MessageType_name = map[int32]string{
	0:  "unknown",
	1:  "document",
	2:  "image",
	3:  "location",
	4:  "system",
	5:  "text",
	6:  "video",
	7:  "voice",
	8:  "audio",
	9:  "template",
	10: "interactive",
}

var MessageType_value = map[string]int32{
	"unknown":     0,
	"document":    1,
	"image":       2,
	"location":    3,
	"system":      4,
	"text":        5,
	"video":       6,
	"voice":       7,
	"audio":       8,
	"template":    9,
	"interactive": 10,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

type Meta_APIStatus int32

const (
	Meta_unknown      Meta_APIStatus = 0
	Meta_deprecated   Meta_APIStatus = 1
	Meta_experimental Meta_APIStatus = 2
	Meta_stable       Meta_APIStatus = 3
)

var Meta_APIStatus_name = map[int32]string{
	0: "unknown",
	1: "deprecated",
	2: "experimental",
	3: "stable",
}

var Meta_APIStatus_value = map[string]int32{
	"unknown":      0,
	"deprecated":   1,
	"experimental": 2,
	"stable":       3,
}

func (x Meta_APIStatus) String() string {
	return proto.EnumName(Meta_APIStatus_name, int32(x))
}

func (Meta_APIStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0, 0}
}

type Meta struct {
	Version              string         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ApiStatus            Meta_APIStatus `protobuf:"varint,2,opt,name=api_status,json=apiStatus,proto3,enum=meta.Meta_APIStatus" json:"api_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return m.Size()
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Meta) GetApiStatus() Meta_APIStatus {
	if m != nil {
		return m.ApiStatus
	}
	return Meta_unknown
}

func init() {
	proto.RegisterEnum("meta.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("meta.Meta_APIStatus", Meta_APIStatus_name, Meta_APIStatus_value)
	proto.RegisterType((*Meta)(nil), "meta.Meta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x6a, 0x2a, 0x41,
	0x10, 0x86, 0x5f, 0xeb, 0x38, 0x3a, 0xa5, 0xf8, 0x8a, 0xc6, 0x85, 0x2b, 0x11, 0x57, 0xf2, 0x16,
	0x3e, 0x88, 0x27, 0x48, 0x16, 0x81, 0x2c, 0x84, 0x60, 0xb2, 0xca, 0x26, 0x94, 0x33, 0x85, 0x34,
	0x99, 0xe9, 0x6e, 0xa6, 0x6b, 0x8c, 0x9e, 0x24, 0xab, 0xdc, 0x27, 0xcb, 0x1c, 0x21, 0x78, 0x92,
	0xd0, 0x13, 0x12, 0xc8, 0xee, 0xab, 0xfa, 0xeb, 0xff, 0x16, 0x05, 0x50, 0xb1, 0xd0, 0xca, 0xd7,
	0x4e, 0x9c, 0x4e, 0x22, 0x2f, 0x5e, 0x15, 0x24, 0x1b, 0x16, 0xd2, 0x53, 0xe8, 0x1f, 0xb8, 0x0e,
	0xc6, 0xd9, 0xa9, 0x9a, 0xab, 0x65, 0xb6, 0xfd, 0x1e, 0xf5, 0x1a, 0x80, 0xbc, 0x79, 0x0c, 0x42,
	0xd2, 0x84, 0x69, 0x67, 0xae, 0x96, 0xe3, 0x8b, 0xc9, 0xaa, 0x35, 0xc5, 0xe6, 0xea, 0xf2, 0xf6,
	0xe6, 0xae, 0xcd, 0xb6, 0x19, 0x79, 0xf3, 0x85, 0x8b, 0x6b, 0xc8, 0x7e, 0xf6, 0x7a, 0x08, 0xfd,
	0xc6, 0x3e, 0x59, 0xf7, 0x6c, 0xf1, 0x8f, 0x1e, 0x03, 0x14, 0xec, 0x6b, 0xce, 0x49, 0xb8, 0x40,
	0xa5, 0x11, 0x46, 0x7c, 0xf4, 0x5c, 0x9b, 0x8a, 0xad, 0x50, 0x89, 0x1d, 0x0d, 0x90, 0x06, 0xa1,
	0x5d, 0xc9, 0xd8, 0xfd, 0xf7, 0xa2, 0x60, 0xb8, 0xe1, 0x10, 0x68, 0xcf, 0xf7, 0x27, 0xcf, 0xbf,
	0x55, 0x23, 0x18, 0x14, 0x2e, 0x6f, 0x62, 0x11, 0x95, 0xce, 0xa0, 0x67, 0x2a, 0xda, 0x33, 0x76,
	0x62, 0x50, 0xba, 0x9c, 0xc4, 0x38, 0x8b, 0xdd, 0xd6, 0x77, 0x0a, 0xc2, 0x15, 0x26, 0x7a, 0x00,
	0x89, 0xf0, 0x51, 0xb0, 0x17, 0xcf, 0x0f, 0xa6, 0x60, 0x87, 0x69, 0x8b, 0xce, 0xe4, 0x8c, 0xfd,
	0x88, 0xd4, 0x14, 0xc6, 0xe1, 0x20, 0x4a, 0x84, 0x2b, 0x5f, 0x92, 0x30, 0x66, 0xfa, 0x2f, 0x0c,
	0x8d, 0x15, 0xae, 0x29, 0x17, 0x73, 0x60, 0x84, 0xab, 0xc9, 0xdb, 0x79, 0xa6, 0xde, 0xcf, 0x33,
	0xf5, 0x71, 0x9e, 0xa9, 0x87, 0xf4, 0x7f, 0xe5, 0x0a, 0x2e, 0x77, 0x69, 0xfb, 0xdc, 0xf5, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0xc9, 0x85, 0xfd, 0x6a, 0x01, 0x00, 0x00,
}

func (m *Meta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Meta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Meta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ApiStatus != 0 {
		i = encodeVarintMeta(dAtA, i, uint64(m.ApiStatus))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMeta(dAtA []byte, offset int, v uint64) int {
	offset -= sovMeta(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Meta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.ApiStatus != 0 {
		n += 1 + sovMeta(uint64(m.ApiStatus))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMeta(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMeta(x uint64) (n int) {
	return sovMeta(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Meta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Meta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Meta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMeta
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiStatus", wireType)
			}
			m.ApiStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApiStatus |= Meta_APIStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMeta(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMeta
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMeta
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMeta
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMeta        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMeta          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMeta = fmt.Errorf("proto: unexpected end of group")
)
