// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: settings.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on RegistrationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RegistrationRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Cc

	// no validation rules for PhoneNumber

	// no validation rules for Method

	// no validation rules for Cert

	// no validation rules for Pin

	return nil
}

// RegistrationRequestValidationError is the validation error returned by
// RegistrationRequest.Validate if the designated constraints aren't met.
type RegistrationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegistrationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegistrationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegistrationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegistrationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegistrationRequestValidationError) ErrorName() string {
	return "RegistrationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegistrationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegistrationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegistrationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegistrationRequestValidationError{}

// Validate checks the field values on VerifyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *VerifyRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Code

	return nil
}

// VerifyRequestValidationError is the validation error returned by
// VerifyRequest.Validate if the designated constraints aren't met.
type VerifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyRequestValidationError) ErrorName() string { return "VerifyRequestValidationError" }

// Error satisfies the builtin error interface
func (e VerifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyRequestValidationError{}

// Validate checks the field values on ApplicationSettings with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ApplicationSettings) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CallbackBackoffDelayMs

	// no validation rules for MaxCallbackBackoffDelayMs

	// no validation rules for CallbackPersist

	if v, ok := interface{}(m.GetMedia()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApplicationSettingsValidationError{
				field:  "Media",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetWebhooks()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ApplicationSettingsValidationError{
				field:  "Webhooks",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PassThrough

	// no validation rules for SentStatus

	// no validation rules for DbGarbagecollectorEnable

	// no validation rules for NotifyUserChangeNumber

	// no validation rules for ShowSecurityNotifications

	return nil
}

// ApplicationSettingsValidationError is the validation error returned by
// ApplicationSettings.Validate if the designated constraints aren't met.
type ApplicationSettingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplicationSettingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplicationSettingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplicationSettingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplicationSettingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplicationSettingsValidationError) ErrorName() string {
	return "ApplicationSettingsValidationError"
}

// Error satisfies the builtin error interface
func (e ApplicationSettingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApplicationSettings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplicationSettingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplicationSettingsValidationError{}

// Validate checks the field values on ProfileAbout with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ProfileAbout) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Text

	return nil
}

// ProfileAboutValidationError is the validation error returned by
// ProfileAbout.Validate if the designated constraints aren't met.
type ProfileAboutValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfileAboutValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfileAboutValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfileAboutValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfileAboutValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfileAboutValidationError) ErrorName() string { return "ProfileAboutValidationError" }

// Error satisfies the builtin error interface
func (e ProfileAboutValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfileAbout.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfileAboutValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfileAboutValidationError{}

// Validate checks the field values on BusinessProfile with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *BusinessProfile) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Address

	// no validation rules for Description

	// no validation rules for Email

	// no validation rules for Vertical

	return nil
}

// BusinessProfileValidationError is the validation error returned by
// BusinessProfile.Validate if the designated constraints aren't met.
type BusinessProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusinessProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusinessProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusinessProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusinessProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusinessProfileValidationError) ErrorName() string { return "BusinessProfileValidationError" }

// Error satisfies the builtin error interface
func (e BusinessProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusinessProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusinessProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusinessProfileValidationError{}

// Validate checks the field values on ApplicationSettings_Media with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ApplicationSettings_Media) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ApplicationSettings_MediaValidationError is the validation error returned by
// ApplicationSettings_Media.Validate if the designated constraints aren't met.
type ApplicationSettings_MediaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplicationSettings_MediaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplicationSettings_MediaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplicationSettings_MediaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplicationSettings_MediaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplicationSettings_MediaValidationError) ErrorName() string {
	return "ApplicationSettings_MediaValidationError"
}

// Error satisfies the builtin error interface
func (e ApplicationSettings_MediaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApplicationSettings_Media.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplicationSettings_MediaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplicationSettings_MediaValidationError{}

// Validate checks the field values on ApplicationSettings_Webhooks with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ApplicationSettings_Webhooks) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Url

	// no validation rules for MaxConcurrentRequests

	return nil
}

// ApplicationSettings_WebhooksValidationError is the validation error returned
// by ApplicationSettings_Webhooks.Validate if the designated constraints
// aren't met.
type ApplicationSettings_WebhooksValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplicationSettings_WebhooksValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplicationSettings_WebhooksValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplicationSettings_WebhooksValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplicationSettings_WebhooksValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplicationSettings_WebhooksValidationError) ErrorName() string {
	return "ApplicationSettings_WebhooksValidationError"
}

// Error satisfies the builtin error interface
func (e ApplicationSettings_WebhooksValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApplicationSettings_Webhooks.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplicationSettings_WebhooksValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplicationSettings_WebhooksValidationError{}
