// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: status.proto

package model

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status_StatusEnum int32

const (
	Status_unknown   Status_StatusEnum = 0
	Status_sent      Status_StatusEnum = 1
	Status_delivered Status_StatusEnum = 2
	Status_read      Status_StatusEnum = 3
)

var Status_StatusEnum_name = map[int32]string{
	0: "unknown",
	1: "sent",
	2: "delivered",
	3: "read",
}

var Status_StatusEnum_value = map[string]int32{
	"unknown":   0,
	"sent":      1,
	"delivered": 2,
	"read":      3,
}

func (x Status_StatusEnum) String() string {
	return proto.EnumName(Status_StatusEnum_name, int32(x))
}

func (Status_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0, 0}
}

type Status struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status_StatusEnum `protobuf:"varint,2,opt,name=status,proto3,enum=whatsapp.Status_StatusEnum" json:"status,omitempty"`
	RecipientId          string            `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Status.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return m.Size()
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Status) GetStatus() Status_StatusEnum {
	if m != nil {
		return m.Status
	}
	return Status_unknown
}

func (m *Status) GetRecipientId() string {
	if m != nil {
		return m.RecipientId
	}
	return ""
}

func (m *Status) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("whatsapp.Status_StatusEnum", Status_StatusEnum_name, Status_StatusEnum_value)
	proto.RegisterType((*Status)(nil), "whatsapp.Status")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x5d, 0xda, 0x60, 0x99, 0xd6, 0x86, 0x6c, 0x3c, 0x10, 0x35, 0x04, 0x7b, 0xe2, 0x52,
	0x48, 0xec, 0xd5, 0x8b, 0x26, 0x1e, 0xbc, 0xe2, 0xcd, 0x8b, 0xd9, 0xb2, 0x93, 0x76, 0x23, 0xec,
	0x6e, 0x60, 0xa0, 0xf6, 0x1f, 0x7a, 0xf0, 0xe0, 0x4f, 0x30, 0xfc, 0x12, 0x23, 0x54, 0x7b, 0xf0,
	0x34, 0x93, 0x37, 0x6f, 0xbe, 0x97, 0x07, 0xb3, 0x9a, 0x04, 0x35, 0x75, 0x62, 0x2b, 0x43, 0x86,
	0x4f, 0x76, 0x5b, 0x41, 0xb5, 0xb0, 0xf6, 0xe2, 0x6e, 0xa3, 0x68, 0xdb, 0xac, 0x93, 0xdc, 0x94,
	0x29, 0xea, 0xd6, 0xec, 0x6d, 0x65, 0xde, 0xf6, 0x69, 0x6f, 0xcb, 0x97, 0x1b, 0xd4, 0xcb, 0x56,
	0x14, 0x4a, 0x0a, 0xc2, 0xf4, 0xdf, 0x32, 0xc0, 0x16, 0x1f, 0x0c, 0xdc, 0xa7, 0x9e, 0xce, 0xe7,
	0xe0, 0x28, 0x19, 0xb0, 0x88, 0xc5, 0x5e, 0xe6, 0x28, 0xc9, 0x57, 0xe0, 0x0e, 0xb9, 0x81, 0x13,
	0xb1, 0x78, 0x7e, 0x73, 0x99, 0xfc, 0x06, 0x27, 0xc3, 0xc7, 0x61, 0x3c, 0xe8, 0xa6, 0xcc, 0x0e,
	0x56, 0x7e, 0x0d, 0xb3, 0x0a, 0x73, 0x65, 0x15, 0x6a, 0x7a, 0x51, 0x32, 0x18, 0xf5, 0xb8, 0xe9,
	0x9f, 0xf6, 0x28, 0xf9, 0x15, 0x78, 0xa4, 0x4a, 0xac, 0x49, 0x94, 0x36, 0x18, 0x47, 0x2c, 0x1e,
	0x65, 0x47, 0x61, 0x71, 0x0b, 0x70, 0xc4, 0xf2, 0x29, 0x9c, 0x36, 0xfa, 0x55, 0x9b, 0x9d, 0xf6,
	0x4f, 0xf8, 0x04, 0xc6, 0x35, 0x6a, 0xf2, 0x19, 0x3f, 0x03, 0x4f, 0x62, 0xa1, 0x5a, 0xac, 0x50,
	0xfa, 0xce, 0xcf, 0xa1, 0x42, 0x21, 0xfd, 0xd1, 0xfd, 0xf9, 0x7b, 0x17, 0xb2, 0xcf, 0x2e, 0x64,
	0x5f, 0x5d, 0xc8, 0x9e, 0xdd, 0xb4, 0x34, 0x12, 0x8b, 0xb5, 0xdb, 0x77, 0x5d, 0x7d, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x32, 0x15, 0x92, 0x48, 0x01, 0x00, 0x00,
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Timestamp != 0 {
		i = encodeVarintStatus(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RecipientId) > 0 {
		i -= len(m.RecipientId)
		copy(dAtA[i:], m.RecipientId)
		i = encodeVarintStatus(dAtA, i, uint64(len(m.RecipientId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintStatus(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintStatus(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStatus(dAtA []byte, offset int, v uint64) int {
	offset -= sovStatus(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovStatus(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovStatus(uint64(m.Status))
	}
	l = len(m.RecipientId)
	if l > 0 {
		n += 1 + l + sovStatus(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovStatus(uint64(m.Timestamp))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovStatus(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStatus(x uint64) (n int) {
	return sovStatus(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStatus
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatus
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatus
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status_StatusEnum(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStatus
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStatus
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStatus(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStatus
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStatus(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStatus
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStatus
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStatus
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStatus
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStatus        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStatus          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStatus = fmt.Errorf("proto: unexpected end of group")
)
